### ISSUE TITLE
schemas: glossary-v1.0.0.json

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/cernopendata#7]
Introduce new JSON Schema representing glossary records. See content at
https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/base/static/json/glossary.json

The ID should probably be lowercase?

**Comment by tiborsimko** [comment]
Note that introducing new record type also means to introduce Elasticsearch mappings, format serialisations and whatnot. I consider it being part of this same ticket.

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko yes in the PR that I have WIP mappings are also added.
